### ISSUE TITLE
Include assets

### ISSUE THREAD

**Issue by ghost** [jguzmanjr1/prj-rev-bwfs-dasmoto#3]
https://github.com/jguzmanjr1/prj-rev-bwfs-dasmoto/blob/master/Dasmotos%20Arts/index.html#L12

Consider including your website's assets (in this case images) in your project and providing a relative file path to them in your `img` tags. 

It's always better to provide static assets up front instead of depending on external URLs that could fail or otherwise become unavailable.

**Comment by jguzmanjr1** [comment]
In this case you mean to save them and add them to the resources folder to be uploaded to GitHub?
